### ISSUE TITLE
Why are we using log(pdf) everywhere?

### ISSUE THREAD

**Issue by MaxNoe** [ibab/python-mle#15]
Wouldn't it be more intuitive to use the pdf and not logp when defining the classes? kogp could be automatically created by the base class (Distribution)

**Comment by ibab** [comment]
Sometimes there are constant terms in the log likelihood that can be left out. These could be detected, but I think it's easier to leave them out explicitly.
Also, this is how pymc and Stan do it, so using logp as well means we can compare our PDF implementations more easily.

**Comment by MaxNoe** [comment]
Don't we get problems when we multiply pdfs if we leave out constants in `log(pdf)`?

**Comment by ibab** [comment]
Multiplication of PDFs becomes addition under `log(pdf)`.

**Comment by MaxNoe** [comment]
of course
