### ISSUE TITLE
Uniform: lower and upper defaults throw errors, not a parameter

### ISSUE THREAD

**Issue by MaxNoe** [ibab/python-mle#17]
The Uniform distribution throws an error with the defaults, as it expects Parameters, not numbers.

**Comment by MaxNoe** [comment]
did an ugly try except block to change this

**Comment by MaxNoe** [comment]
fixed in 30b417e45d971d2d8b68e93cf0100703ddb09763

**Comment by ibab** [comment]
We should spend some time thinking about what should happen if numbers are passed in instead of a parameter. We could automatically create a new constant parameter or just put the number into the likelihood. This is something that will need to be done for all distributions.
